preload = /home/ren/dotfiles/hypr/.config/hypr/wallpapers/your_name.jpg
wallpaper = HDMI-A-1,/home/ren/dotfiles/hypr/.config/hypr/wallpapers/your_name.jpg
wallpaper = eDP-2,/home/ren/dotfiles/hypr/.config/hypr/wallpapers/your_name.jpg
wallpaper = DP-2,/home/ren/dotfiles/hypr/.config/hypr/wallpapers/your_name.jpg

# 1. Manually "Preload" the file into memory
# hyprctl hyprpaper preload "/home/ren/dotfiles/hypr/.config/hypr/wallpapers/your_name.jpg"
#
# # 2. Manually "Apply" it to the monitors
# hyprctl hyprpaper wallpaper "eDP-1,/home/ren/dotfiles/hypr/.config/hypr/wallpapers/your_name.jpg"
# hyprctl hyprpaper wallpaper "HDMI-A-5,/home/ren/dotfiles/hypr/.config/hypr/wallpapers/your_name.jpg"
# hyprctl hyprpaper wallpaper "DP-4,/home/ren/dotfiles/hypr/.config/hypr/wallpapers/your_name.jpg"
